// Code generated by goyacc -l -o parser.go parser.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

type yySymType struct {
	yys  int
	node Node
	item Token
}

const DASH = 57346
const DIV = 57347
const DOT = 57348
const DIGIT = 57349
const BLANK = 57350
const COLON = 57351
const COMMA = 57352
const EOF = 57353
const ERROR = 57354
const SPACE = 57355
const MONTH = 57356
const HANYEAR = 57357
const HANMONTH = 57358
const HANDAY = 57359
const keywordsStart = 57360
const JANUARY = 57361
const JAN = 57362
const FEBRUARY = 57363
const FEB = 57364
const MARCH = 57365
const MAR = 57366
const APRIL = 57367
const APR = 57368
const MAY = 57369
const JUNE = 57370
const JUN = 57371
const JULY = 57372
const JUL = 57373
const AUGUST = 57374
const AUG = 57375
const SEPTEMBER = 57376
const SEPT = 57377
const OCTOBER = 57378
const OCT = 57379
const NOVEMBER = 57380
const NOV = 57381
const DECEMBER = 57382
const DEC = 57383
const keywordsEnd = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DASH",
	"DIV",
	"DOT",
	"DIGIT",
	"BLANK",
	"COLON",
	"COMMA",
	"EOF",
	"ERROR",
	"SPACE",
	"MONTH",
	"HANYEAR",
	"HANMONTH",
	"HANDAY",
	"keywordsStart",
	"JANUARY",
	"JAN",
	"FEBRUARY",
	"FEB",
	"MARCH",
	"MAR",
	"APRIL",
	"APR",
	"MAY",
	"JUNE",
	"JUN",
	"JULY",
	"JUL",
	"AUGUST",
	"AUG",
	"SEPTEMBER",
	"SEPT",
	"OCTOBER",
	"OCT",
	"NOVEMBER",
	"NOV",
	"DECEMBER",
	"DEC",
	"keywordsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 7,
	13, 17,
	-2, 14,
	-1, 16,
	13, 16,
	-2, 13,
}

const yyPrivate = 57344

const yyLast = 57

var yyAct = [...]int{
	3, 11, 9, 51, 4, 32, 5, 55, 49, 36,
	8, 29, 10, 17, 20, 21, 22, 18, 25, 23,
	7, 26, 15, 34, 19, 27, 45, 6, 13, 14,
	50, 37, 28, 53, 38, 44, 40, 46, 41, 42,
	43, 52, 48, 24, 39, 35, 30, 16, 31, 12,
	54, 33, 1, 47, 2, 0, 56,
}

var yyPact = [...]int{
	13, -1000, -1000, -3, 44, 15, 16, 40, 10, 10,
	10, 10, 36, 10, 36, 12, 25, -2, 39, -1000,
	43, -11, 47, 18, 38, -4, 21, 36, 37, 36,
	-1000, 36, 36, 36, 19, -1000, 35, -5, 20, -1000,
	-1000, -1000, -14, -1000, -1000, 34, -1000, -1000, 26, 19,
	-6, -1000, 25, 25, -1000, 19, -1000,
}

var yyPgo = [...]int{
	0, 54, 0, 4, 6, 53, 52,
}

var yyR1 = [...]int{
	0, 6, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 5, 3, 3, 3, 4, 4,
}

var yyR2 = [...]int{
	0, 1, 5, 5, 6, 5, 5, 5, 5, 6,
	7, 4, 2, 2, 1, 1, 2, 1,
}

var yyChk = [...]int{
	-1000, -6, -1, -2, -3, -4, 14, 7, 13, 5,
	15, 4, 5, 13, 13, 6, 7, -3, 7, 14,
	-3, -3, -3, -4, 7, -3, -4, 13, 7, 13,
	7, 5, 16, 4, 5, 7, 13, 10, -4, 7,
	-4, -4, -4, -4, -2, 7, -2, -5, 7, 13,
	10, 17, 7, 7, -2, 13, -2,
}

var yyDef = [...]int{
	0, -2, 1, 0, 0, 0, 15, -2, 0, 0,
	0, 0, 0, 0, 0, 0, -2, 0, 14, 15,
	0, 0, 0, 0, 17, 0, 0, 0, 0, 0,
	13, 0, 0, 0, 0, 16, 0, 0, 0, 11,
	2, 3, 0, 6, 5, 0, 7, 8, 0, 0,
	0, 4, 0, 12, 9, 0, 10,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).Result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[1].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[5].node.(Day))}
		}
	case 3:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[1].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[5].node.(Day))}
		}
	case 4:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[1].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[5].node.(Day))}
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[5].node.(Year)), Month: int(yyDollar[1].node.(Month)), Day: int(yyDollar[3].node.(Day))}
		}
	case 6:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[1].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[5].node.(Day))}
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[5].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[1].node.(Day))}
		}
	case 8:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Date{Year: int(yyDollar[5].node.(Year)), Month: int(yyDollar[3].node.(Month)), Day: int(yyDollar[1].node.(Day))}
		}
	case 9:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			var m = ConvToManth(yyDollar[1].item.Val)
			yyVAL.node = &Date{Year: int(yyDollar[6].node.(Year)), Month: int(m), Day: int(yyDollar[3].node.(Day))}
		}
	case 10:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			var m = ConvToManth(yyDollar[1].item.Val)
			yyVAL.node = &Date{Year: int(yyDollar[7].node.(Year)), Month: int(m), Day: int(yyDollar[4].node.(Day))}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = JoinYear(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item, yyDollar[4].item)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = JoinYear(yyDollar[1].item, yyDollar[2].item)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = JoinMonth(yyDollar[1].item, yyDollar[2].item)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = JoinMonth(yyDollar[1].item)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = ConvToManth(yyDollar[1].item.Val)
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = JoinDay(yyDollar[1].item, yyDollar[2].item)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = JoinDay(yyDollar[1].item)
		}
	}
	goto yystack /* stack new state and value */
}
